"""SQLite-backed store for ARTi's cross-project aggregators -- project-index.md,
research-idea-bank.md, and idea-index.md -- plus the dashboard's own project
registry, which shares this file's `project_index` table (the dashboard reads
and writes it directly via dashboard/server/db.py). One connection per call,
guarded by a module-level lock, no ORM, no pip deps. Every write auto-
regenerates the matching markdown file so the plain-text views stay current
without a separate export step.
"""
import json
import re
import sqlite3
import threading
from datetime import datetime
from pathlib import Path

ARTI_HOME = Path(__file__).resolve().parent.parent.parent
DB_PATH = ARTI_HOME / "memory" / "arti.db"

LEGACY_PROJECT_INDEX_PATH = ARTI_HOME / "memory" / "project-index.md"
LEGACY_IDEA_BANK_PATH = ARTI_HOME / "memory" / "research-idea-bank.md"
LEGACY_IDEA_INDEX_PATH = ARTI_HOME / "inbox" / "idea-index.md"
LEGACY_LAUNCHER_DB_PATH = ARTI_HOME / "memory" / "launcher.db"

EXPORT_BANNER = "> Generated by `arti-db ... export` -- do not hand-edit, changes will be overwritten."

_lock = threading.Lock()

SCHEMA = """
CREATE TABLE IF NOT EXISTS project_index (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  topic          TEXT NOT NULL,
  project_path   TEXT NOT NULL UNIQUE,
  stage          TEXT NOT NULL,
  target_journal TEXT,
  status         TEXT,
  summary        TEXT,
  updated_at     TEXT NOT NULL,
  created_at     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS idea_bank (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  label          TEXT NOT NULL,
  idea_text      TEXT NOT NULL,
  novelty_c      INTEGER,
  novelty_m      INTEGER,
  novelty_e      INTEGER,
  novelty_label  TEXT,
  date_parked    TEXT NOT NULL,
  source_project TEXT,
  reason_parked  TEXT,
  notes          TEXT,
  tag            TEXT,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS idea_index (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  project      TEXT NOT NULL,
  file         TEXT NOT NULL,
  tipe         TEXT NOT NULL DEFAULT 'Ide',
  status       TEXT,
  hook         TEXT,
  used_in      TEXT,
  date_added   TEXT NOT NULL,
  archived     INTEGER NOT NULL DEFAULT 0,
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL,
  UNIQUE(project, file)
);

CREATE TABLE IF NOT EXISTS idea_index_log (
  id   INTEGER PRIMARY KEY AUTOINCREMENT,
  ts   TEXT NOT NULL,
  note TEXT NOT NULL
);
"""


def _today():
    return datetime.now().strftime("%Y-%m-%d")


def _now():
    return datetime.now().isoformat(timespec="seconds")


def _connect():
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH, timeout=5)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=5000")
    return conn


def _row_to_dict(row):
    return dict(row) if row is not None else None


def init_db():
    """Creates the schema (idempotent) and, the first time arti.db does not
    exist yet, one-time imports the three legacy markdown files. The markdown
    files are left in place -- they become generated exports afterward, not
    deleted."""
    is_new = not DB_PATH.exists()
    with _lock:
        conn = _connect()
        try:
            existing_tables = {r["name"] for r in conn.execute(
                "SELECT name FROM sqlite_master WHERE type='table'"
            ).fetchall()}
            if "progress" in existing_tables and "project_index" not in existing_tables:
                conn.execute("ALTER TABLE progress RENAME TO project_index")
                conn.commit()
            conn.executescript(SCHEMA)
            conn.commit()
            cols = {r["name"] for r in conn.execute("PRAGMA table_info(project_index)").fetchall()}
            if "summary" not in cols:
                conn.execute("ALTER TABLE project_index ADD COLUMN summary TEXT")
                conn.commit()
            cols = {r["name"] for r in conn.execute("PRAGMA table_info(project_index)").fetchall()}
            if "category" not in cols:
                conn.execute("ALTER TABLE project_index ADD COLUMN category TEXT NOT NULL DEFAULT 'Paper'")
                conn.execute("ALTER TABLE project_index ADD COLUMN tags TEXT NOT NULL DEFAULT '[]'")
                conn.execute("ALTER TABLE project_index ADD COLUMN lifecycle TEXT NOT NULL DEFAULT 'active'")
                conn.execute("ALTER TABLE project_index ADD COLUMN added_at TEXT")
                conn.execute("ALTER TABLE project_index ADD COLUMN last_opened_at TEXT")
                conn.execute("UPDATE project_index SET added_at = created_at WHERE added_at IS NULL")
                conn.commit()
                _migrate_launcher_db(conn)
                conn.commit()
            cols = {r["name"] for r in conn.execute("PRAGMA table_info(idea_bank)").fetchall()}
            if "tag" not in cols:
                conn.execute("ALTER TABLE idea_bank ADD COLUMN tag TEXT")
                conn.commit()
            if is_new:
                _migrate_legacy(conn)
                conn.commit()
        finally:
            conn.close()
    if is_new:
        project_export()
        idea_bank_export()
        idea_index_export()


def _migrate_legacy(conn):
    if LEGACY_PROJECT_INDEX_PATH.exists():
        for row in _parse_project_index_md(LEGACY_PROJECT_INDEX_PATH):
            try:
                now = _now()
                conn.execute(
                    "INSERT OR IGNORE INTO project_index "
                    "(topic, project_path, stage, target_journal, status, summary, updated_at, created_at) "
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                    (row["topic"], row["project_path"], row["stage"],
                     row["target_journal"], row["status"], row.get("summary"), row["updated_at"], now),
                )
            except Exception as e:
                print(f"warning: skipped project_index row {row!r}: {e}", file=_stderr())

    if LEGACY_IDEA_BANK_PATH.exists():
        for row in _parse_idea_bank_md(LEGACY_IDEA_BANK_PATH):
            try:
                now = _now()
                conn.execute(
                    "INSERT INTO idea_bank "
                    "(label, idea_text, novelty_c, novelty_m, novelty_e, novelty_label, "
                    "date_parked, source_project, reason_parked, notes, created_at, updated_at) "
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                    (row["label"], row["idea_text"], row["novelty_c"], row["novelty_m"],
                     row["novelty_e"], row["novelty_label"], row["date_parked"],
                     row["source_project"], row["reason_parked"], row.get("notes"), now, now),
                )
            except Exception as e:
                print(f"warning: skipped idea_bank row {row!r}: {e}", file=_stderr())

    if LEGACY_IDEA_INDEX_PATH.exists():
        rows, log_lines = _parse_idea_index_md(LEGACY_IDEA_INDEX_PATH)
        for row in rows:
            try:
                now = _now()
                conn.execute(
                    "INSERT OR IGNORE INTO idea_index "
                    "(project, file, tipe, status, hook, used_in, date_added, archived, created_at, updated_at) "
                    "VALUES (?, ?, ?, ?, ?, ?, ?, 0, ?, ?)",
                    (row["project"], row["file"], row["tipe"], row["status"],
                     row["hook"], row["used_in"], row["date_added"], now, now),
                )
            except Exception as e:
                print(f"warning: skipped idea_index row {row!r}: {e}", file=_stderr())
        for ts, note in log_lines:
            try:
                conn.execute(
                    "INSERT INTO idea_index_log (ts, note) VALUES (?, ?)", (ts, note)
                )
            except Exception as e:
                print(f"warning: skipped idea_index_log line {note!r}: {e}", file=_stderr())


def _migrate_launcher_db(conn):
    """One-time import of the dashboard's now-retired launcher.db `projects`
    table, run exactly once -- from the same "category column just added"
    branch in init_db() that can never re-run. Matches launcher rows onto
    existing project_index rows by path (the paper projects scaffolded
    through the dashboard, present in both stores already); anything
    unmatched (Dev/Other projects, or a Paper project never scaffolded via
    the dashboard) becomes a new project_index row."""
    if not LEGACY_LAUNCHER_DB_PATH.exists():
        return
    launcher_conn = sqlite3.connect(LEGACY_LAUNCHER_DB_PATH)
    launcher_conn.row_factory = sqlite3.Row
    try:
        launcher_rows = launcher_conn.execute("SELECT * FROM projects").fetchall()
    except sqlite3.OperationalError:
        return
    finally:
        launcher_conn.close()

    now = _now()
    for row in launcher_rows:
        path = row["path"]
        existing = conn.execute(
            "SELECT id FROM project_index WHERE project_path = ?", (path,)
        ).fetchone()
        if existing is not None:
            conn.execute(
                "UPDATE project_index SET category=?, tags=?, lifecycle=?, added_at=?, last_opened_at=? "
                "WHERE project_path=?",
                (row["category"], row["tags"], row["lifecycle"], row["added_at"],
                 row["last_opened_at"], path),
            )
        else:
            conn.execute(
                "INSERT INTO project_index "
                "(topic, project_path, stage, target_journal, status, summary, updated_at, created_at, "
                "category, tags, lifecycle, added_at, last_opened_at) "
                "VALUES (?, ?, 'N/A', NULL, NULL, NULL, ?, ?, ?, ?, ?, ?, ?)",
                (row["name"], path, now, now,
                 row["category"], row["tags"], row["lifecycle"], row["added_at"], row["last_opened_at"]),
            )


def _stderr():
    import sys
    return sys.stderr


def _parse_project_index_md(path):
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 6:
            continue
        if cells[0].lower().startswith("topic"):
            continue
        if all(re.fullmatch(r":?-+:?", c) for c in cells):
            continue
        has_summary = len(cells) >= 7
        rows.append({
            "topic": cells[0],
            "project_path": cells[1],
            "stage": cells[2],
            "target_journal": cells[3] if cells[3] != "—" else None,
            "status": cells[4],
            "summary": (cells[5] if cells[5] != "—" else None) if has_summary else None,
            "updated_at": cells[6] if has_summary else cells[5],
        })
    return rows


_ENTRY_RE = re.compile(r"^## Entry (\d+):\s*(.+)$", re.MULTILINE)
_FIELD_RE = re.compile(r"^\*\*([^*]+):\*\*\s*(.*)$")


def _parse_idea_bank_md(path):
    text = path.read_text(encoding="utf-8")
    blocks = re.split(r"(?=^## Entry \d+:)", text, flags=re.MULTILINE)
    rows = []
    for block in blocks:
        m = _ENTRY_RE.search(block)
        if not m:
            continue
        label = m.group(2).strip()
        fields = {}
        current_key = None
        for line in block.splitlines():
            fm = _FIELD_RE.match(line.strip())
            if fm:
                current_key = fm.group(1).strip().lower()
                fields[current_key] = fm.group(2).strip()
            elif current_key and line.strip():
                fields[current_key] += " " + line.strip()
        idea_text = fields.get("idea text", "")
        novelty = fields.get("novelty score", "")
        nm = re.search(r"C(\d+)\s*/\s*M(\d+)\s*/\s*E(\d+)\s*(?:→\s*(.+))?", novelty)
        c = m2 = e = None
        label_n = None
        if nm:
            c, m2, e, label_n = int(nm.group(1)), int(nm.group(2)), int(nm.group(3)), nm.group(4)
        rows.append({
            "label": label,
            "idea_text": idea_text,
            "novelty_c": c,
            "novelty_m": m2,
            "novelty_e": e,
            "novelty_label": label_n.strip() if label_n else None,
            "date_parked": fields.get("date parked", _today()),
            "source_project": fields.get("source project/topic"),
            "reason_parked": fields.get("reason parked"),
            "notes": None,
        })
    return rows


def _parse_idea_index_md(path):
    text = path.read_text(encoding="utf-8")
    rows = []
    in_table = False
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("| Project"):
            in_table = True
            continue
        if in_table and s.startswith("|"):
            cells = [c.strip() for c in s.strip("|").split("|")]
            if len(cells) < 7:
                continue
            if all(re.fullmatch(r":?-+:?", c) for c in cells):
                continue
            rows.append({
                "project": cells[0],
                "file": cells[1],
                "tipe": cells[2] or "Ide",
                "status": cells[3],
                "hook": cells[4],
                "used_in": cells[5] if cells[5] != "—" else None,
                "date_added": cells[6],
            })
        elif in_table and not s.startswith("|"):
            in_table = False

    log_lines = []
    log_re = re.compile(r"^- (\d{4}-\d{2}-\d{2}(?:\s+\d{2}:\d{2})?)\s*—\s*(.+)$")
    in_log = False
    buf_ts, buf_note = None, None
    for line in text.splitlines():
        if line.strip() == "## Change log":
            in_log = True
            continue
        if not in_log:
            continue
        m = log_re.match(line)
        if m:
            if buf_ts is not None:
                log_lines.append((buf_ts, buf_note.strip()))
            buf_ts, buf_note = m.group(1), m.group(2)
        elif buf_ts is not None and line.strip():
            buf_note += " " + line.strip()
    if buf_ts is not None:
        log_lines.append((buf_ts, buf_note.strip()))
    return rows, log_lines


# ---------------------------------------------------------------------------
# project_index
# ---------------------------------------------------------------------------

def project_upsert(project_path, topic, stage=None, target_journal=None, status=None, summary=None, updated=None):
    updated = updated or _today()
    with _lock:
        conn = _connect()
        try:
            row = conn.execute(
                "SELECT * FROM project_index WHERE project_path = ?", (project_path,)
            ).fetchone()
            now = _now()
            if row is None:
                conn.execute(
                    "INSERT INTO project_index (topic, project_path, stage, target_journal, status, summary, updated_at, created_at) "
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                    (topic, project_path, stage or "Not started", target_journal, status, summary, updated, now),
                )
            else:
                entry = _row_to_dict(row)
                new_stage = stage if stage is not None else entry["stage"]
                new_journal = target_journal if target_journal is not None else entry["target_journal"]
                new_status = status if status is not None else entry["status"]
                new_summary = summary if summary is not None else entry["summary"]
                conn.execute(
                    "UPDATE project_index SET topic=?, stage=?, target_journal=?, status=?, summary=?, updated_at=? "
                    "WHERE project_path=?",
                    (topic, new_stage, new_journal, new_status, new_summary, updated, project_path),
                )
            conn.commit()
            result = _row_to_dict(
                conn.execute("SELECT * FROM project_index WHERE project_path = ?", (project_path,)).fetchone()
            )
        finally:
            conn.close()
    project_export()
    return result


def project_list(stage=None, status=None):
    with _lock:
        conn = _connect()
        try:
            query = "SELECT * FROM project_index WHERE 1=1"
            params = []
            if stage:
                query += " AND stage = ?"
                params.append(stage)
            if status:
                query += " AND status = ?"
                params.append(status)
            query += " ORDER BY topic"
            rows = conn.execute(query, params).fetchall()
            return [_row_to_dict(r) for r in rows]
        finally:
            conn.close()


def project_get(project_path):
    with _lock:
        conn = _connect()
        try:
            row = conn.execute(
                "SELECT * FROM project_index WHERE project_path = ?", (project_path,)
            ).fetchone()
            return _row_to_dict(row)
        finally:
            conn.close()


def project_export():
    with _lock:
        conn = _connect()
        try:
            rows = conn.execute("SELECT * FROM project_index ORDER BY topic").fetchall()
            rows = [_row_to_dict(r) for r in rows]
        finally:
            conn.close()

    lines = [
        "# Idea/Paper Project Index",
        "",
        "**File location:** `~/.arti/memory/project-index.md` — one row per project folder, so the",
        "researcher can see everything in flight without opening each project individually.",
        "",
        EXPORT_BANNER,
        "",
        "> Claude upserts a project's row at **phase boundaries only** — project scaffolded, idea",
        "> complete (handoff written), writing started, submitted, published. Not once per stage: rewriting",
        "> this file five times during idea development costs more upkeep than the overview is worth. The",
        "> dashboard (`~/.arti/dashboard/`) reads and writes this same `project_index` table directly for",
        "> its own launcher fields (category/tags/lifecycle) — this markdown export covers every row.",
        "",
        "---",
        "",
        "| Topic / idea label | Project folder path | Current stage | Target journal | Status | Summary | Last updated |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['topic']} | {r['project_path']} | {r['stage']} | {r['target_journal'] or '—'} "
            f"| {r['status'] or ''} | {r['summary'] or '—'} | {r['updated_at']} |"
        )
    LEGACY_PROJECT_INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    LEGACY_PROJECT_INDEX_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# idea_bank
# ---------------------------------------------------------------------------

def idea_bank_add(label, idea_text, c=None, m=None, e=None, novelty_label=None,
                   date_parked=None, source_project=None, reason_parked=None, notes=None, tag=None):
    date_parked = date_parked or _today()
    now = _now()
    with _lock:
        conn = _connect()
        try:
            cur = conn.execute(
                "INSERT INTO idea_bank (label, idea_text, novelty_c, novelty_m, novelty_e, "
                "novelty_label, date_parked, source_project, reason_parked, notes, tag, created_at, updated_at) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (label, idea_text, c, m, e, novelty_label, date_parked, source_project,
                 reason_parked, notes, tag, now, now),
            )
            conn.commit()
            row = _row_to_dict(
                conn.execute("SELECT * FROM idea_bank WHERE id = ?", (cur.lastrowid,)).fetchone()
            )
        finally:
            conn.close()
    idea_bank_export()
    return row


def idea_bank_search(keywords):
    like_terms = [f"%{k}%" for k in keywords]
    with _lock:
        conn = _connect()
        try:
            clauses = []
            params = []
            for term in like_terms:
                clauses.append(
                    "(idea_text LIKE ? OR label LIKE ? OR source_project LIKE ? OR notes LIKE ?)"
                )
                params.extend([term, term, term, term])
            query = "SELECT * FROM idea_bank"
            if clauses:
                query += " WHERE " + " AND ".join(clauses)
            query += " ORDER BY date_parked DESC"
            rows = conn.execute(query, params).fetchall()
            return [_row_to_dict(r) for r in rows]
        finally:
            conn.close()


def idea_bank_list(source_project=None):
    with _lock:
        conn = _connect()
        try:
            if source_project:
                rows = conn.execute(
                    "SELECT * FROM idea_bank WHERE source_project = ? ORDER BY date_parked DESC",
                    (source_project,),
                ).fetchall()
            else:
                rows = conn.execute("SELECT * FROM idea_bank ORDER BY date_parked DESC").fetchall()
            return [_row_to_dict(r) for r in rows]
        finally:
            conn.close()


def idea_bank_remove(id_):
    with _lock:
        conn = _connect()
        try:
            row = conn.execute("SELECT * FROM idea_bank WHERE id = ?", (id_,)).fetchone()
            conn.execute("DELETE FROM idea_bank WHERE id = ?", (id_,))
            conn.commit()
        finally:
            conn.close()
    idea_bank_export()
    return _row_to_dict(row)


def idea_bank_export():
    with _lock:
        conn = _connect()
        try:
            rows = conn.execute("SELECT * FROM idea_bank ORDER BY id").fetchall()
            rows = [_row_to_dict(r) for r in rows]
        finally:
            conn.close()

    lines = [
        "# Research Idea Bank",
        "",
        "**Scope:** research/paper-topic ideas only — candidate future studies parked from the Idea Canvas.",
        "For anything else (framework/skill ideas, workflow friction, general raw ideas from any project's",
        "`inbox/`), see `~/.arti/inbox/idea-index.md` instead.",
        "",
        "**File location:** `~/.arti/memory/research-idea-bank.md` (persistent, cross-project — not inside",
        "any single project folder)",
        "",
        EXPORT_BANNER,
        "",
        "> Auto-populated. Any idea that clears Meaningful-or-above on the Idea Canvas (Stage 3) but is",
        "> not the one selected to advance is appended here automatically — never silently discarded.",
        "> At the start of every new Gap Map (Stage 2), Claude checks this file first and surfaces any",
        "> entry relevant to the new topic before generating fresh ideas from zero.",
        "",
        "---",
        "",
    ]
    for r in rows:
        lines.append(f"## Entry {r['id']}: {r['label']}")
        lines.append(f"**Idea text:** {r['idea_text']}")
        if r["novelty_c"] is not None:
            lines.append(
                f"**Novelty score:** C{r['novelty_c']} / M{r['novelty_m']} / E{r['novelty_e']} "
                f"→ {r['novelty_label'] or ''}"
            )
        lines.append(f"**Date parked:** {r['date_parked']}")
        lines.append(f"**Source project/topic:** {r['source_project'] or ''}")
        if r["reason_parked"]:
            lines.append(f"**Reason parked:** {r['reason_parked']}")
        if r["notes"]:
            lines.append(f"**Notes:** {r['notes']}")
        if r.get("tag"):
            lines.append(f"**Tag:** {r['tag']}")
        lines.append("")
    LEGACY_IDEA_BANK_PATH.parent.mkdir(parents=True, exist_ok=True)
    LEGACY_IDEA_BANK_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# idea_index
# ---------------------------------------------------------------------------

def idea_index_upsert(project, file, tipe="Ide", status=None, hook=None, used_in=None, date_added=None):
    date_added = date_added or _today()
    now = _now()
    with _lock:
        conn = _connect()
        try:
            row = conn.execute(
                "SELECT * FROM idea_index WHERE project = ? AND file = ?", (project, file)
            ).fetchone()
            if row is None:
                conn.execute(
                    "INSERT INTO idea_index (project, file, tipe, status, hook, used_in, date_added, "
                    "archived, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, 0, ?, ?)",
                    (project, file, tipe, status, hook, used_in, date_added, now, now),
                )
            else:
                entry = _row_to_dict(row)
                conn.execute(
                    "UPDATE idea_index SET tipe=?, status=?, hook=?, used_in=?, date_added=?, updated_at=? "
                    "WHERE project=? AND file=?",
                    (tipe or entry["tipe"], status if status is not None else entry["status"],
                     hook if hook is not None else entry["hook"],
                     used_in if used_in is not None else entry["used_in"],
                     date_added, now, project, file),
                )
            conn.commit()
            result = _row_to_dict(
                conn.execute(
                    "SELECT * FROM idea_index WHERE project = ? AND file = ?", (project, file)
                ).fetchone()
            )
        finally:
            conn.close()
    idea_index_export()
    return result


def idea_index_list(project=None, status=None, include_archived=False):
    with _lock:
        conn = _connect()
        try:
            query = "SELECT * FROM idea_index WHERE 1=1"
            params = []
            if not include_archived:
                query += " AND archived = 0"
            if project:
                query += " AND project = ?"
                params.append(project)
            if status:
                query += " AND status = ?"
                params.append(status)
            query += " ORDER BY date_added"
            rows = conn.execute(query, params).fetchall()
            return [_row_to_dict(r) for r in rows]
        finally:
            conn.close()


def idea_index_archive(ids, summary):
    now = _now()
    with _lock:
        conn = _connect()
        try:
            conn.executemany(
                "UPDATE idea_index SET archived = 1, updated_at = ? WHERE id = ?",
                [(now, i) for i in ids],
            )
            conn.execute(
                "INSERT INTO idea_index_log (ts, note) VALUES (?, ?)", (now, summary)
            )
            conn.commit()
            rows = conn.execute(
                f"SELECT * FROM idea_index WHERE id IN ({','.join('?' * len(ids))})", ids
            ).fetchall()
            result = [_row_to_dict(r) for r in rows]
        finally:
            conn.close()
    idea_index_export()
    return result


def idea_index_log(note):
    now = _now()
    with _lock:
        conn = _connect()
        try:
            cur = conn.execute(
                "INSERT INTO idea_index_log (ts, note) VALUES (?, ?)", (now, note)
            )
            conn.commit()
            row = _row_to_dict(
                conn.execute("SELECT * FROM idea_index_log WHERE id = ?", (cur.lastrowid,)).fetchone()
            )
        finally:
            conn.close()
    idea_index_export()
    return row


def idea_index_export():
    with _lock:
        conn = _connect()
        try:
            rows = conn.execute(
                "SELECT * FROM idea_index WHERE archived = 0 ORDER BY date_added"
            ).fetchall()
            rows = [_row_to_dict(r) for r in rows]
            log_rows = conn.execute(
                "SELECT * FROM idea_index_log ORDER BY ts DESC"
            ).fetchall()
            log_rows = [_row_to_dict(r) for r in log_rows]
        finally:
            conn.close()

    lines = [
        "# Idea List Index",
        "",
        "**File location:** `~/.arti/inbox/idea-index.md` — a `project-index.md`-style aggregator: one row",
        "per raw idea captured in any project's `inbox/` folder (this project's own `inbox/` included), so",
        "\"what's my idea list and status\" is answered by reading this one file, no per-project scanning",
        "needed.",
        "",
        EXPORT_BANNER,
        "",
        "> Distinct from `~/.arti/inbox/index.md` (scoped to ideas about the ARTi framework/skills",
        "> themselves) and from `~/.arti/memory/research-idea-bank.md` (scoped to research/paper-topic",
        "> ideas parked from the Idea Canvas). This file covers everything captured via the `inbox/`",
        "> convention, across every kind of idea and every project.",
        "",
        "> Claude upserts a row here the moment an idea is triaged (OK/SKIP/PARKED) in any project's",
        "> `inbox/index.md` — the same touch-point pattern `project-index.md` already uses for paper-stage",
        "> upserts.",
        "",
        "---",
        "",
        "| Project | File | Tipe | Status | One-line hook | Dipakai di | Date added |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['project']} | {r['file']} | {r['tipe']} | {r['status'] or '(untriaged)'} "
            f"| {r['hook'] or ''} | {r['used_in'] or '—'} | {r['date_added']} |"
        )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Change log")
    for lr in log_rows:
        lines.append(f"- {lr['ts']} — {lr['note']}")
    LEGACY_IDEA_INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    LEGACY_IDEA_INDEX_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
