"""SQLite-backed store for a single paper project's bibliography -- Layer 2
(`literature\\library.md`, canonical) and Layer 3 (`writing\\references.md`,
generated per-draft reference list) of ARTi-writing's Reference System. Unlike
`tools/arti-db` (a cross-project singleton under `~/.arti`), this tool is
per-project: it resolves its data file relative to `--project` (default cwd),
since bibliography data belongs to one paper project, not the framework as a
whole. One connection per call, guarded by a module-level lock, no ORM, no pip
deps. Every write auto-regenerates `literature\\library.md` so the plain-text
view stays current without a separate export step.
"""
import re
import sqlite3
import threading
from datetime import datetime
from pathlib import Path

EXPORT_BANNER = "> Generated by `arti-lit library export` -- do not hand-edit, changes will be overwritten."

_lock = threading.Lock()

SCHEMA = """
CREATE TABLE IF NOT EXISTS sources (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  key          TEXT NOT NULL UNIQUE,
  citation     TEXT NOT NULL,
  doi          TEXT,
  local_file   TEXT,
  read_status  TEXT NOT NULL DEFAULT 'export-only',
  used_in      TEXT,
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);
"""

READ_STATUSES = ("export-only", "abstract", "fulltext", "read")


def _now():
    return datetime.now().isoformat(timespec="seconds")


def _paths(project):
    root = Path(project).resolve() if project else Path.cwd()
    return {
        "root": root,
        "db": root / "literature" / "arti-lit.db",
        "legacy_library": root / "literature" / "library.md",
    }


def _connect(db_path):
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path, timeout=5)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=5000")
    return conn


def _row_to_dict(row):
    return dict(row) if row is not None else None


def init_db(project=None):
    """Creates the schema (idempotent) and, the first time arti-lit.db does
    not exist yet, one-time imports literature\\library.md. The markdown file
    is left in place -- it becomes a generated export afterward, not
    deleted."""
    paths = _paths(project)
    is_new = not paths["db"].exists()
    with _lock:
        conn = _connect(paths["db"])
        try:
            conn.executescript(SCHEMA)
            conn.commit()
            if is_new:
                _migrate_legacy(conn, paths["legacy_library"])
                conn.commit()
        finally:
            conn.close()
    if is_new:
        library_export(project)
    return paths


def _migrate_legacy(conn, legacy_path):
    if not legacy_path.exists():
        return
    for row in _parse_library_md(legacy_path):
        try:
            now = _now()
            conn.execute(
                "INSERT OR IGNORE INTO sources "
                "(key, citation, doi, local_file, read_status, used_in, created_at, updated_at) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                (row["key"], row["citation"], row["doi"], row["local_file"],
                 row["read_status"], row["used_in"], now, now),
            )
        except Exception as e:
            print(f"warning: skipped library row {row!r}: {e}", file=_stderr())


def _stderr():
    import sys
    return sys.stderr


def _parse_library_md(path):
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 6:
            continue
        if cells[0].lower().startswith("key"):
            continue
        if all(re.fullmatch(r":?-+:?", c) for c in cells):
            continue
        rows.append({
            "key": cells[0],
            "citation": cells[1],
            "doi": cells[2] if cells[2] not in ("", "—") else None,
            "local_file": cells[3] if cells[3] not in ("", "—") else None,
            "read_status": cells[4] if cells[4] else "export-only",
            "used_in": cells[5] if cells[5] not in ("", "—") else None,
        })
    return rows


# ---------------------------------------------------------------------------
# library
# ---------------------------------------------------------------------------

def library_add(project, key, citation, doi=None, local_file=None,
                 read_status="export-only", used_in=None):
    paths = _paths(project)
    with _lock:
        conn = _connect(paths["db"])
        try:
            if doi:
                dupe = conn.execute(
                    "SELECT key FROM sources WHERE doi = ? AND doi IS NOT NULL AND key != ?",
                    (doi, key),
                ).fetchone()
                if dupe is not None:
                    raise ValueError(
                        f"DOI {doi!r} already exists on key {dupe['key']!r} -- dedupe instead of adding"
                    )
            now = _now()
            conn.execute(
                "INSERT INTO sources (key, citation, doi, local_file, read_status, used_in, created_at, updated_at) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                (key, citation, doi, local_file, read_status, used_in, now, now),
            )
            conn.commit()
            row = _row_to_dict(conn.execute("SELECT * FROM sources WHERE key = ?", (key,)).fetchone())
        finally:
            conn.close()
    library_export(project)
    return row


def library_update(project, key, citation=None, doi=None, local_file=None,
                    read_status=None, used_in=None):
    paths = _paths(project)
    with _lock:
        conn = _connect(paths["db"])
        try:
            row = conn.execute("SELECT * FROM sources WHERE key = ?", (key,)).fetchone()
            if row is None:
                raise ValueError(f"no source with key {key!r}")
            entry = _row_to_dict(row)
            if doi:
                dupe = conn.execute(
                    "SELECT key FROM sources WHERE doi = ? AND doi IS NOT NULL AND key != ?",
                    (doi, key),
                ).fetchone()
                if dupe is not None:
                    raise ValueError(
                        f"DOI {doi!r} already exists on key {dupe['key']!r} -- dedupe instead of updating"
                    )
            new_citation = citation if citation is not None else entry["citation"]
            new_doi = doi if doi is not None else entry["doi"]
            new_local_file = local_file if local_file is not None else entry["local_file"]
            new_read_status = read_status if read_status is not None else entry["read_status"]
            new_used_in = used_in if used_in is not None else entry["used_in"]
            conn.execute(
                "UPDATE sources SET citation=?, doi=?, local_file=?, read_status=?, used_in=?, updated_at=? "
                "WHERE key=?",
                (new_citation, new_doi, new_local_file, new_read_status, new_used_in, _now(), key),
            )
            conn.commit()
            result = _row_to_dict(conn.execute("SELECT * FROM sources WHERE key = ?", (key,)).fetchone())
        finally:
            conn.close()
    library_export(project)
    return result


def library_get(project, key):
    paths = _paths(project)
    with _lock:
        conn = _connect(paths["db"])
        try:
            return _row_to_dict(conn.execute("SELECT * FROM sources WHERE key = ?", (key,)).fetchone())
        finally:
            conn.close()


def library_list(project, status=None):
    paths = _paths(project)
    with _lock:
        conn = _connect(paths["db"])
        try:
            if status:
                rows = conn.execute(
                    "SELECT * FROM sources WHERE read_status = ? ORDER BY key", (status,)
                ).fetchall()
            else:
                rows = conn.execute("SELECT * FROM sources ORDER BY key").fetchall()
            return [_row_to_dict(r) for r in rows]
        finally:
            conn.close()


def library_search(project, keywords):
    paths = _paths(project)
    like_terms = [f"%{k}%" for k in keywords]
    with _lock:
        conn = _connect(paths["db"])
        try:
            clauses = []
            params = []
            for term in like_terms:
                clauses.append("(citation LIKE ? OR key LIKE ? OR used_in LIKE ?)")
                params.extend([term, term, term])
            query = "SELECT * FROM sources"
            if clauses:
                query += " WHERE " + " AND ".join(clauses)
            query += " ORDER BY key"
            rows = conn.execute(query, params).fetchall()
            return [_row_to_dict(r) for r in rows]
        finally:
            conn.close()


def library_remove(project, key):
    paths = _paths(project)
    with _lock:
        conn = _connect(paths["db"])
        try:
            row = conn.execute("SELECT * FROM sources WHERE key = ?", (key,)).fetchone()
            conn.execute("DELETE FROM sources WHERE key = ?", (key,))
            conn.commit()
            result = _row_to_dict(row)
        finally:
            conn.close()
    library_export(project)
    return result


def library_export(project=None):
    paths = _paths(project)
    with _lock:
        conn = _connect(paths["db"])
        try:
            rows = conn.execute("SELECT * FROM sources ORDER BY key").fetchall()
            rows = [_row_to_dict(r) for r in rows]
        finally:
            conn.close()

    lines = [
        "# Literature Library",
        "",
        "**File location:** `literature\\library.md` — canonical bibliography, one source per line,",
        "superset including screened-out sources. See ARTi-writing's Reference System (Layer 2).",
        "",
        EXPORT_BANNER,
        "",
        "---",
        "",
        "| key | citation | DOI | local file | read-status | used-in |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['key']} | {r['citation']} | {r['doi'] or '—'} | {r['local_file'] or '—'} "
            f"| {r['read_status']} | {r['used_in'] or '—'} |"
        )
    paths["legacy_library"].parent.mkdir(parents=True, exist_ok=True)
    paths["legacy_library"].write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# refs (Layer 3)
# ---------------------------------------------------------------------------

_KEY_RE = re.compile(r"^(.*?)-(\d{4})([a-z]?)$")


def _key_sort_tuple(key):
    m = _KEY_RE.match(key)
    if not m:
        return (key, "", "")
    author, year, suffix = m.groups()
    return (author.lower(), year, suffix)


def refs_generate(project, keys, order="alpha", output=None):
    paths = _paths(project)
    seen = set()
    ordered_keys = []
    for k in keys:
        if k not in seen:
            seen.add(k)
            ordered_keys.append(k)

    with _lock:
        conn = _connect(paths["db"])
        try:
            rows_by_key = {}
            for k in ordered_keys:
                row = conn.execute("SELECT * FROM sources WHERE key = ?", (k,)).fetchone()
                if row is not None:
                    rows_by_key[k] = _row_to_dict(row)
        finally:
            conn.close()

    unresolved = [k for k in ordered_keys if k not in rows_by_key]
    resolved_keys = [k for k in ordered_keys if k in rows_by_key]
    if order == "alpha":
        resolved_keys = sorted(resolved_keys, key=_key_sort_tuple)
    elif order != "appearance":
        raise ValueError(f"unknown order {order!r} -- must be 'alpha' or 'appearance'")

    out_path = Path(output).resolve() if output else paths["root"] / "writing" / "references.md"
    lines = [
        "# References",
        "",
        EXPORT_BANNER.replace("library export", "refs generate"),
        "",
    ]
    for i, k in enumerate(resolved_keys, start=1):
        lines.append(f"{i}. {rows_by_key[k]['citation']}")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    return {"written": len(resolved_keys), "unresolved": unresolved, "output": str(out_path)}
